import hmac
import hashlib
import json
import time

class ZeroTrustCryptography:
    """
    Implements Zero-Trust Architecture for IIoT Telemetry.
    Prevents Man-in-the-Middle (MitM) and Stuxnet-style physical spoofing.
    Uses HMAC-SHA256 as a lightweight proxy for ECDSA.
    """
    def __init__(self, secret_key: str = "B3ta_K3y_M1ss1on_Cr1t1cal_001"):
        self.secret_key = secret_key.encode('utf-8')

    def sign_payload(self, payload: dict) -> str:
        """
        Executed on the EDGE DEVICE (Hardware Sensor).
        Cryptographically signs the telemetry payload.
        """
        # Ensure consistent ordering for JSON stringification to prevent hash mismatch
        payload_str = json.dumps(payload, sort_keys=True).encode('utf-8')
        
        # Generate HMAC SHA256 Signature
        signature = hmac.new(self.secret_key, payload_str, hashlib.sha256).hexdigest()
        return signature

    def verify_payload(self, payload: dict, provided_signature: str) -> bool:
        """
        Executed on the CLOUD SERVER (PetroFlow Backend).
        Verifies that the payload was generated by a trusted sensor and hasn't been altered.
        """
        expected_signature = self.sign_payload(payload)
        
        # Use hmac.compare_digest to prevent timing attacks
        return hmac.compare_digest(expected_signature, provided_signature)

class StuxnetPreventionFirewall:
    """Simulates the Edge-to-Cloud firewall intercepting telemetry."""
    def __init__(self):
        self.crypto = ZeroTrustCryptography()
        
    def process_incoming_mqtt_message(self, raw_message: dict) -> dict:
        """Validates incoming messages before passing to the math engines."""
        if "signature" not in raw_message:
            raise PermissionError("SECURITY BREACH: Unsigned payload intercepted. Dropping packet.")
            
        signature = raw_message.pop("signature")
        payload = raw_message
        
        # Verify timestamp to prevent Replay Attacks (e.g. replaying an old "healthy" signal)
        if time.time() - payload.get("timestamp", 0) > 60:
            raise PermissionError("SECURITY BREACH: Replay attack detected. Packet too old.")
            
        if not self.crypto.verify_payload(payload, signature):
            raise PermissionError("SECURITY BREACH: Cryptographic signature mismatch. Payload was tampered in transit.")
            
        return payload
