"""
Report Service for FastAPI Backend
Migrated from core/report_generator.py
Generates professional PDF reports for maintenance, diagnostics, and analysis
"""

import io
import logging
from datetime import datetime
from typing import Dict, Any, Optional, List
from pathlib import Path

try:
    from fpdf import FPDF
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False
    logging.warning("fpdf2 not installed. PDF generation will be disabled.")

from sqlalchemy.orm import Session
from app.models.equipment import Equipment
from app.models.simulation import Simulation
from app.models.analysis import AnalysisResult

logger = logging.getLogger(__name__)


class PetroFlowReport(FPDF):
    """Custom PDF report class with PetroFlow branding."""
    
    def __init__(self, report_title: str = "PetroFlow Report"):
        super().__init__()
        self.report_title = report_title
    
    def header(self):
        """Add header to each page."""
        self.set_font("helvetica", "B", 20)
        self.set_text_color(25, 35, 55)
        self.cell(0, 10, "PetroFlow Enterprise", border=False, ln=True, align="L")
        
        self.set_font("helvetica", "I", 12)
        self.set_text_color(100, 110, 130)
        self.cell(0, 10, self.report_title, border=False, ln=True, align="L")
        self.ln(10)
    
    def footer(self):
        """Add footer to each page."""
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by PetroFlow SaaS", align="C")
    
    def add_section_title(self, title: str):
        """Add a section title."""
        self.set_font("helvetica", "B", 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, title, ln=True)
        self.ln(2)
    
    def add_parameter_table(self, parameters: Dict[str, Any], title: str = "Parameters"):
        """Add a parameter table to the report."""
        self.add_section_title(title)
        
        self.set_font("helvetica", "", 11)
        self.set_fill_color(240, 245, 250)
        
        # Header
        self.cell(90, 10, "Parameter", border=1, fill=True)
        self.cell(90, 10, "Value", border=1, fill=True, ln=True)
        
        # Data rows
        for key, value in parameters.items():
            self.cell(90, 10, str(key), border=1)
            self.cell(90, 10, str(value), border=1, ln=True)
        
        self.ln(5)
    
    def add_status_banner(self, status: str, message: str, is_critical: bool = False):
        """Add a status banner."""
        self.set_font("helvetica", "B", 14)
        
        if is_critical:
            self.set_text_color(220, 53, 69)  # Red
        else:
            self.set_text_color(40, 167, 69)  # Green
        
        self.multi_cell(0, 10, f"{status}: {message}")
        self.ln(5)


class ReportService:
    """
    Service for generating various types of reports.
    Supports PDF generation for maintenance, diagnostics, and analysis.
    """
    
    def __init__(self):
        """Initialize report service."""
        if not PDF_AVAILABLE:
            logger.error("PDF generation not available. Install fpdf2: pip install fpdf2")
        
        self.enabled = PDF_AVAILABLE
        logger.info("Report Service initialized")
    
    def generate_maintenance_report(
        self,
        db: Session,
        equipment_id: int,
        simulation_data: Optional[Dict[str, Any]] = None
    ) -> bytes:
        """
        Generate maintenance diagnostic report.
        
        Args:
            db: Database session
            equipment_id: Equipment ID
            simulation_data: Optional simulation results
        
        Returns:
            PDF report as bytes
        """
        if not self.enabled:
            raise RuntimeError("PDF generation not available")
        
        equipment = db.query(Equipment).filter(Equipment.id == equipment_id).first()
        if not equipment:
            raise ValueError(f"Equipment {equipment_id} not found")
        
        pdf = PetroFlowReport("Maintenance Diagnostic Report")
        pdf.add_page()
        
        # Metadata
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        pdf.cell(0, 8, f"Report Date: {fecha}", ln=True)
        pdf.cell(0, 8, f"Equipment: {equipment.tag} - {equipment.name}", ln=True)
        pdf.cell(0, 8, f"Type: {equipment.equipment_type.value}", ln=True)
        pdf.cell(0, 8, f"Status: {equipment.status.value}", ln=True)
        pdf.ln(10)
        
        # Equipment specifications
        if equipment.specifications:
            pdf.add_parameter_table(equipment.specifications, "Equipment Specifications")
        
        # Operating parameters
        if equipment.operating_parameters:
            pdf.add_parameter_table(equipment.operating_parameters, "Current Operating Parameters")
        
        # Simulation results if provided
        if simulation_data:
            self._add_simulation_section(pdf, simulation_data)
        
        # Recommendations
        pdf.add_section_title("Maintenance Recommendations")
        pdf.set_font("helvetica", "", 11)
        
        recommendations = self._generate_recommendations(equipment, simulation_data)
        for i, rec in enumerate(recommendations, 1):
            pdf.multi_cell(0, 8, f"{i}. {rec}")
        
        return pdf.output(dest="S").encode("latin-1")
    
    def generate_simulation_report(
        self,
        db: Session,
        simulation_id: int
    ) -> bytes:
        """
        Generate simulation analysis report.
        
        Args:
            db: Database session
            simulation_id: Simulation ID
        
        Returns:
            PDF report as bytes
        """
        if not self.enabled:
            raise RuntimeError("PDF generation not available")
        
        simulation = db.query(Simulation).filter(Simulation.id == simulation_id).first()
        if not simulation:
            raise ValueError(f"Simulation {simulation_id} not found")
        
        equipment = simulation.equipment
        
        pdf = PetroFlowReport("Simulation Analysis Report")
        pdf.add_page()
        
        # Metadata
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 8, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.cell(0, 8, f"Simulation ID: SIM-{simulation.id}", ln=True)
        pdf.cell(0, 8, f"Equipment: {equipment.tag} - {equipment.name}", ln=True)
        pdf.cell(0, 8, f"Simulation Type: {simulation.simulation_type}", ln=True)
        pdf.cell(0, 8, f"Status: {simulation.status.value}", ln=True)
        pdf.ln(10)
        
        # Status banner
        is_critical = simulation.results and simulation.results.get('is_stressed', False)
        status_msg = self._get_simulation_status_message(simulation.results, is_critical)
        pdf.add_status_banner(
            "CRITICAL" if is_critical else "NORMAL",
            status_msg,
            is_critical
        )
        
        # Simulation parameters
        if simulation.parameters:
            pdf.add_parameter_table(simulation.parameters, "Simulation Parameters")
        
        # Results
        if simulation.results:
            pdf.add_parameter_table(simulation.results, "Simulation Results")
        
        return pdf.output(dest="S").encode("latin-1")
    
    def generate_analysis_report(
        self,
        db: Session,
        analysis_id: int
    ) -> bytes:
        """
        Generate analysis results report.
        
        Args:
            db: Database session
            analysis_id: Analysis ID
        
        Returns:
            PDF report as bytes
        """
        if not self.enabled:
            raise RuntimeError("PDF generation not available")
        
        analysis = db.query(AnalysisResult).filter(AnalysisResult.id == analysis_id).first()
        if not analysis:
            raise ValueError(f"Analysis {analysis_id} not found")
        
        equipment = analysis.equipment
        
        pdf = PetroFlowReport("Equipment Analysis Report")
        pdf.add_page()
        
        # Metadata
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 8, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.cell(0, 8, f"Analysis ID: ANA-{analysis.id}", ln=True)
        pdf.cell(0, 8, f"Equipment: {equipment.tag} - {equipment.name}", ln=True)
        pdf.cell(0, 8, f"Analysis Type: {analysis.analysis_type}", ln=True)
        pdf.ln(10)
        
        # Analysis parameters
        if analysis.parameters:
            pdf.add_parameter_table(analysis.parameters, "Analysis Parameters")
        
        # Results
        if analysis.results:
            pdf.add_parameter_table(analysis.results, "Analysis Results")
        
        # Interpretation
        pdf.add_section_title("Result Interpretation")
        pdf.set_font("helvetica", "", 11)
        interpretation = self._interpret_analysis_results(analysis)
        pdf.multi_cell(0, 8, interpretation)
        
        return pdf.output(dest="S").encode("latin-1")
    
    def generate_what_if_report(
        self,
        db: Session,
        equipment_id: int,
        baseline_params: Dict[str, Any],
        simulated_params: Dict[str, Any],
        results: Dict[str, Any]
    ) -> bytes:
        """
        Generate What-If scenario analysis report.
        
        Args:
            db: Database session
            equipment_id: Equipment ID
            baseline_params: Baseline operating parameters
            simulated_params: Simulated parameters
            results: Simulation results
        
        Returns:
            PDF report as bytes
        """
        if not self.enabled:
            raise RuntimeError("PDF generation not available")
        
        equipment = db.query(Equipment).filter(Equipment.id == equipment_id).first()
        if not equipment:
            raise ValueError(f"Equipment {equipment_id} not found")
        
        pdf = PetroFlowReport("What-If Scenario Analysis")
        pdf.add_page()
        
        # Metadata
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        pdf.cell(0, 8, f"Report Date: {fecha}", ln=True)
        pdf.cell(0, 8, f"Equipment: {equipment.tag}", ln=True)
        pdf.cell(0, 8, f"Analysis ID: WIF-{int(datetime.now().timestamp())}", ln=True)
        pdf.ln(10)
        
        # Status banner
        is_stressed = results.get('is_stressed', False)
        baseline_health = results.get('baseline_health', 100)
        simulated_health = results.get('simulated_health', 100)
        
        if is_stressed:
            status_msg = "CRITICAL: Simulated parameters significantly reduce equipment lifespan"
        else:
            status_msg = "STABLE: Simulated parameters are within safe operating range"
        
        pdf.add_status_banner(
            "CRITICAL" if is_stressed else "STABLE",
            status_msg,
            is_stressed
        )
        
        # Baseline parameters
        pdf.add_parameter_table(baseline_params, "Baseline Parameters")
        
        # Simulated parameters
        pdf.add_parameter_table(simulated_params, "Simulated Parameters")
        
        # Health impact
        pdf.add_section_title("Equipment Health Impact")
        pdf.set_font("helvetica", "", 11)
        pdf.set_fill_color(240, 245, 250)
        
        pdf.cell(90, 10, "Baseline Health", border=1, fill=True)
        pdf.cell(90, 10, "Simulated Health", border=1, fill=True, ln=True)
        
        pdf.cell(90, 10, f"{baseline_health:.1f}%", border=1)
        
        if is_stressed:
            pdf.set_text_color(220, 53, 69)
        else:
            pdf.set_text_color(40, 167, 69)
        
        pdf.cell(90, 10, f"{simulated_health:.1f}%", border=1, ln=True)
        pdf.set_text_color(0, 0, 0)
        
        return pdf.output(dest="S").encode("latin-1")
    
    def generate_fleet_report(
        self,
        db: Session,
        equipment_ids: List[int]
    ) -> bytes:
        """
        Generate fleet-wide equipment report.
        
        Args:
            db: Database session
            equipment_ids: List of equipment IDs
        
        Returns:
            PDF report as bytes
        """
        if not self.enabled:
            raise RuntimeError("PDF generation not available")
        
        pdf = PetroFlowReport("Fleet Equipment Report")
        pdf.add_page()
        
        # Metadata
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 8, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.cell(0, 8, f"Equipment Count: {len(equipment_ids)}", ln=True)
        pdf.ln(10)
        
        # Equipment summary table
        pdf.add_section_title("Equipment Summary")
        pdf.set_font("helvetica", "", 9)
        pdf.set_fill_color(240, 245, 250)
        
        # Header
        pdf.cell(30, 8, "Tag", border=1, fill=True)
        pdf.cell(50, 8, "Name", border=1, fill=True)
        pdf.cell(30, 8, "Type", border=1, fill=True)
        pdf.cell(30, 8, "Status", border=1, fill=True)
        pdf.cell(30, 8, "Critical", border=1, fill=True, ln=True)
        
        # Data rows
        for eq_id in equipment_ids:
            equipment = db.query(Equipment).filter(Equipment.id == eq_id).first()
            if equipment:
                pdf.cell(30, 8, equipment.tag[:15], border=1)
                pdf.cell(50, 8, equipment.name[:25], border=1)
                pdf.cell(30, 8, equipment.equipment_type.value, border=1)
                pdf.cell(30, 8, equipment.status.value, border=1)
                pdf.cell(30, 8, "Yes" if equipment.is_critical else "No", border=1, ln=True)
        
        return pdf.output(dest="S").encode("latin-1")
    
    def _add_simulation_section(self, pdf: PetroFlowReport, simulation_data: Dict[str, Any]):
        """Add simulation results section to PDF."""
        pdf.add_section_title("Simulation Results")
        
        if 'vibration' in simulation_data:
            pdf.set_font("helvetica", "", 11)
            pdf.cell(0, 8, f"Vibration: {simulation_data['vibration']:.2f} mm/s", ln=True)
        
        if 'temperature' in simulation_data:
            pdf.cell(0, 8, f"Temperature: {simulation_data['temperature']:.2f} °C", ln=True)
        
        if 'rpm' in simulation_data:
            pdf.cell(0, 8, f"Speed: {simulation_data['rpm']:.2f} RPM", ln=True)
        
        pdf.ln(5)
    
    def _generate_recommendations(
        self,
        equipment: Equipment,
        simulation_data: Optional[Dict[str, Any]]
    ) -> List[str]:
        """Generate maintenance recommendations based on equipment and simulation data."""
        recommendations = []
        
        # Check operating hours
        if equipment.operating_hours and equipment.operating_hours > 8000:
            recommendations.append(
                f"Equipment has {equipment.operating_hours:.0f} operating hours. "
                "Schedule comprehensive inspection."
            )
        
        # Check maintenance schedule
        if equipment.next_maintenance_date:
            days_until = (equipment.next_maintenance_date - datetime.now()).days
            if days_until < 30:
                recommendations.append(
                    f"Scheduled maintenance due in {days_until} days. "
                    "Prepare maintenance resources."
                )
        
        # Check simulation results
        if simulation_data:
            if simulation_data.get('is_stressed', False):
                recommendations.append(
                    "Simulation indicates stressed operating conditions. "
                    "Reduce operating parameters or schedule early maintenance."
                )
            
            health = simulation_data.get('simulated_health', 100)
            if health < 70:
                recommendations.append(
                    f"Equipment health at {health:.1f}%. "
                    "Immediate inspection recommended."
                )
        
        # Default recommendation
        if not recommendations:
            recommendations.append("Equipment operating within normal parameters. Continue routine monitoring.")
        
        return recommendations
    
    def _get_simulation_status_message(
        self,
        results: Optional[Dict[str, Any]],
        is_critical: bool
    ) -> str:
        """Generate status message from simulation results."""
        if not results:
            return "Simulation completed successfully"
        
        if is_critical:
            return "Simulated parameters indicate critical operating conditions"
        else:
            return "Simulated parameters are within acceptable operating range"
    
    def _interpret_analysis_results(self, analysis: AnalysisResult) -> str:
        """Generate interpretation text for analysis results."""
        if not analysis.results:
            return "No results available for interpretation."
        
        analysis_type = analysis.analysis_type
        results = analysis.results
        
        if analysis_type == "performance":
            efficiency = results.get('efficiency', 0)
            if efficiency > 90:
                return f"Equipment performance is excellent at {efficiency:.1f}% efficiency."
            elif efficiency > 75:
                return f"Equipment performance is acceptable at {efficiency:.1f}% efficiency."
            else:
                return f"Equipment performance is below optimal at {efficiency:.1f}% efficiency. Investigation recommended."
        
        elif analysis_type == "health":
            health_score = results.get('health_score', 0)
            if health_score > 85:
                return f"Equipment health is good with a score of {health_score:.1f}."
            elif health_score > 70:
                return f"Equipment health is fair with a score of {health_score:.1f}. Monitor closely."
            else:
                return f"Equipment health is poor with a score of {health_score:.1f}. Immediate action required."
        
        else:
            return f"Analysis of type '{analysis_type}' completed successfully. Review detailed results above."


# Singleton instance
_report_service = None

def get_report_service() -> ReportService:
    """Get singleton report service instance."""
    global _report_service
    if _report_service is None:
        _report_service = ReportService()
    return _report_service