"""add_mfa_and_oauth

Revision ID: 9100386d1f08
Revises: 001
Create Date: 2026-05-21 17:49:01.593165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9100386d1f08'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep legacy tables intact to prevent any data loss
    # op.drop_table('personal_mantenimiento')
    # op.drop_table('storage_archivos')
    # op.drop_table('reportes_intervencion')
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_picture', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('oauth_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('oauth_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'oauth_token_expires_at')
    op.drop_column('users', 'oauth_refresh_token')
    op.drop_column('users', 'oauth_access_token')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'google_picture')
    op.drop_column('users', 'google_email')
    op.drop_column('users', 'google_id')
    op.create_table('reportes_intervencion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('equipo_id', sa.TEXT(), nullable=False),
    sa.Column('equipo_nombre', sa.TEXT(), nullable=True),
    sa.Column('tipo_intervencion', sa.TEXT(), nullable=True),
    sa.Column('descripcion_falla', sa.TEXT(), nullable=True),
    sa.Column('descripcion_trabajo', sa.TEXT(), nullable=True),
    sa.Column('tecnico_id', sa.INTEGER(), nullable=True),
    sa.Column('fecha_inicio', sa.DATETIME(), nullable=True),
    sa.Column('fecha_fin', sa.DATETIME(), nullable=True),
    sa.Column('duracion_horas', sa.FLOAT(), nullable=True),
    sa.Column('costo_estimado', sa.FLOAT(), nullable=True),
    sa.Column('repuestos_utilizados', sa.TEXT(), nullable=True),
    sa.Column('prioridad', sa.TEXT(), nullable=True),
    sa.Column('estado_reporte', sa.TEXT(), nullable=True),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['personal_mantenimiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_archivos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_archivo', sa.TEXT(), nullable=False),
    sa.Column('tipo_archivo', sa.TEXT(), nullable=True),
    sa.Column('ruta_almacenamiento', sa.TEXT(), nullable=False),
    sa.Column('tamano_bytes', sa.INTEGER(), nullable=True),
    sa.Column('hash_md5', sa.TEXT(), nullable=True),
    sa.Column('entidad_relacionada', sa.TEXT(), nullable=True),
    sa.Column('entidad_id', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_by', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_mantenimiento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_completo', sa.TEXT(), nullable=False),
    sa.Column('cedula', sa.TEXT(), nullable=False),
    sa.Column('especialidad', sa.TEXT(), nullable=True),
    sa.Column('nivel_certificacion', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('telefono', sa.TEXT(), nullable=True),
    sa.Column('foto_perfil_path', sa.TEXT(), nullable=True),
    sa.Column('fecha_ingreso', sa.DATETIME(), nullable=True),
    sa.Column('estado', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    # ### end Alembic commands ###