#!/usr/bin/env python
import sys
sys.path.insert(0, '.')
print('IMPORT app.database')
import app.database
print('OK app.database')
print('IMPORT app.schemas.equipment')
import app.schemas.equipment
print('OK app.schemas.equipment')
print('IMPORT app.core.equipment_engine')
import app.core.equipment_engine
print('OK app.core.equipment_engine')
print('IMPORT app.api.deps')
import app.api.deps
print('OK app.api.deps')
print('IMPORT app.models.user')
import app.models.user
print('OK app.models.user')
